project:
  type: book

book:
  title: "Learn Data Skills"
  author: "Data Engineering Community"
  date: "2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrbook



